name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo desde GithuActions"

  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Segundo Hola mundo
        run: echo "Hola Mundo de nuevo"
