name: Deploy to server 2

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log

      - name: Subit artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test-enrique
          path: test.log

  second_job:
    runs-on: ubuntu-latest

    ## crear dependencia para que el job se corra despues de primero y tener el archivo generado. sino dara error porque el artifact no existe
    needs: first_job

    steps:
      - name: Descagar el artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test-enrique

      - name: Cat file
        run: cat test.log
